all_classes = {'mage': {'dodge': 0,
                        'max reduction': 10,
                        'main stat': 'intelligence',
                        'hp counter': 2,
                        'magic': 1},
               'warrior': {'dodge': 25,
                           'max reduction': 50,
                           'main stat': 'strength',
                           'hp counter': 5,
                           'magic': 0},
               'scout': {'dodge': 50,
                         'max reduction': 25,
                         'main stat': 'dexterity',
                         'hp counter': 4,
                         'magic': 0},
               'battle mage': {'dodge': 0,
                               'max reduction': 50,
                               'main stat': 'strength',
                               'hp counter': 5,
                               'magic': 1},
               'berserker': {'dodge': 0,
                             'max reduction': 25,
                             'main stat': 'strength',
                             'hp counter': 4,
                             'magic': 0},
               'assassin': {'dodge': 0,
                            'max reduction': 25,
                            'main stat': 'dexterity',
                            'hp counter': 4,
                            'magic': 0},
               'demon hunter': {'dodge': 0,
                                'max reduction': 50,
                                'main stat': 'dexterity',
                                'hp counter': 4,
                                'magic': 0},
               'druid': {'dodge': 0,
                         'max reduction': 50,
                         'main stat': 'intelligence',
                         'hp counter': 2,
                         'magic': 0}
               }
